---
name: arkose_labs_signup_challenge
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95560
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/370932
milestone: '15.4'
type: development
group: group::anti-abuse
default_enabled: false
