---
name: block_emails_with_failures
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96902
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/373159
milestone: '15.4'
type: development
group: group::project management
default_enabled: false
