---
name: changelog_commits_limitation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/89032
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/364101
milestone: '15.1'
type: development
group: group::source code
default_enabled: true
