---
name: ci_limit_active_jobs_early
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97700
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/373284
milestone: '15.4'
type: development
group: group::pipeline execution
default_enabled: false
