---
name: ci_update_unlocked_pipeline_artifacts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97228
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372835
milestone: '15.4'
type: development
group: group::pipeline insights
default_enabled: false
