---
name: ci_variable_settings_graphql
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/89332
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/364423
milestone: '15.1'
type: development
group: group::pipeline authoring
default_enabled: false
