---
name: container_registry_migration_phase2_capacity_5
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/85908
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/350543
milestone: '15.0'
type: development
group: group::package
default_enabled: false
