---
name: container_registry_migration_phase2_capacity_25
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/79061
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/350543
milestone: '14.8'
type: development
group: group::package
default_enabled: false
