---
name: disabled_mr_discussions_redis_cache
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92752
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368366
milestone: '15.3'
type: development
group: group::code review
default_enabled: false
