---
name: enable_vulnerability_remediations_from_records
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/362283
milestone: '15.1'
type: development
group: group::threat insights
default_enabled: false
