---
name: exit_registration_verification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/80286
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/352397
milestone: '14.8'
type: development
group: group::activation
default_enabled: false
