---
name: file_line_blame
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92538
rollout_issue_url: 
milestone: '15.3'
type: development
group: group::source code
default_enabled: false
