---
name: global_search_custom_slis
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95182
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372107
milestone: '15.4'
type: development
group: group::application performance
default_enabled: false
