---
name: group_overview_tabs_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95850
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/370872
milestone: '15.4'
type: development
group: group::workspace
default_enabled: false
