---
name: hash_oauth_secrets
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96252
rollout_issue_url: 
milestone: '15.4'
type: development
group: group::authentication and authorization
default_enabled: false
