---
name: include_groups_from_group_shares_in_group_transfer_locations
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96347
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/371961
milestone: '15.4'
type: development
group: group::workspace
default_enabled: false
