---
name: job_log_jump_to_failures
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91098
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368633
milestone: '15.3'
type: development
group: group::pipeline execution
default_enabled: false
