---
name: markdown_dollar_math
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/94111
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/371180
milestone: '15.4'
type: development
group: group::project management
default_enabled: false
