---
name: markup_rendering_timeout
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/89509
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/365358
milestone: '15.1'
type: development
group: group::source code
default_enabled: false
