---
name: optimized_project_and_group_activity_queries
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/85810
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/360458
milestone: '15.0'
type: development
group: group::workspace
default_enabled: false
