---
name: pages_lets_encrypt_ecdsa
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/88125
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/363026
milestone: '15.1'
type: development
group: group::editor
default_enabled: false
