---
name: process_issue_closure_in_background
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/94981
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/371024
milestone: '15.4'
type: development
group: group::source code
default_enabled: false
