---
name: product_intelligence_database_event_tracking
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92079
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368976
milestone: '15.3'
type: development
group: group::product intelligence
default_enabled: false
