---
name: rate_limit_gitlab_shell_by_ip
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91599
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/367998
milestone: '15.3'
type: development
group: group::source code
default_enabled: false
