---
name: registry_migration_guard_dynamic_pre_import_timeout
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/88292
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/350543
milestone: '15.1'
type: development
group: group::package
default_enabled: false
