---
name: route_hll_to_snowplow
introduced_by_url: https://gitlab.com/gitlab-org/product-intelligence/-/issues/498
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/354442
milestone: '14.9'
type: development
group: group::product intelligence
default_enabled: true
