---
name: run_pipeline_graphql
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96633
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372310
milestone: '15.4'
type: development
group: group::pipeline authoring
default_enabled: false
