---
name: scan_execution_rule_mode
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/90099
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/359883
milestone: '15.2'
type: development
group: group::container security
default_enabled: false
