---
name: ultimate_feature_removal_banner
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/94271
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/371690
milestone: '15.4'
type: development
group: group::workspace
default_enabled: false
