---
name: usage_data_ci_i_testing_test_report_uploaded
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95112
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/339720
milestone: '15.4'
type: development
group: group::pipeline insights
default_enabled: false
