---
name: use_traversal_ids_for_descendants_scopes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78542
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/350637
milestone: '14.8'
type: development
group: group::authentication and authorization
default_enabled: true
