---
name: webui_members_inherited_users
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/83214
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/364078
milestone: '15.4'
type: development
group: group::workspace
default_enabled: false
