---
name: auditor_group_runner_access
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91553
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368089
milestone: '15.3'
type: development
group: group::runner
default_enabled: false
