---
name: deprecate_vulnerabilities_feedback
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/86497
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/361797
milestone: '15.0'
type: development
group: group::threat insights
default_enabled: false
