---
name: enforce_storage_limit_for_free
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82704
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/356767
milestone: '14.10'
type: development
group: group::utilization
default_enabled: false
