---
name: epic_color_highlight
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/79940
rollout_issue_url:
milestone: '14.9'
type: development
group: group::product planning
default_enabled: false
