---
name: identity_verification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95722
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/371389
milestone: '15.4'
type: development
group: group::anti-abuse
default_enabled: false
