---
name: immediate_delete_subgroup_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92508
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368276
milestone: '15.3'
type: development
group: group::workspace
default_enabled: true
