---
name: limit_unique_project_downloads_per_namespace_user
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/89996
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/365724
milestone: '15.2'
type: development
group: group::anti-abuse
default_enabled: false
