---
name: refactor_vulnerability_tool_filter
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/93003
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368325
milestone: '15.3'
type: development
group: group::threat insights
default_enabled: false
