---
name: registration_trial_in_background
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97692
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/373271
milestone: '15.4'
type: development
group: group::acquisition
default_enabled: false
