---
name: suggested_reviewers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92847
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368356
milestone: '15.3'
type: development
group: group::applied ml
default_enabled: false
