---
name: verification_reminder
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/75123
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/346828
milestone: "14.6"
type: development
group: group::activation
default_enabled: false
