---
description: Perform Git operation (read/write/push)
category: EventCreateService
action: action_active_users_project_repo
label_description:
property_description:
value_description:
extra_properties:
identifiers:
product_section: dev
product_stage: create
product_group: group::source code
product_category: source_code_management
milestone: "15.0"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/83795
distributions:
- ce
- ee
tiers: 
- free
- premium
- ultimate

