---
description: Triggered from backend layer when merge request is created
category: merge_request_action
action: create
label_description: Constant string that match with ServicePing metric name of merge_requests_users
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: dev
product_stage: create
product_group: group::code review
product_category: code_review
milestone: "15.1"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/89544
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate

