---
description: Feature flag not enabled on the GitLab instance
category: Projects::GoogleCloud::ConfigurationController
action: error_feature_flag_not_enabled
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: google_cloud
product_stage: configure
product_group: group::incubation
product_category: cloud_seed
milestone: "15.4"
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96683"
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate

