stages:
  - prepare

# valid cache:when values
job1:
  stage: prepare
  script:
    - echo 'running job'
  cache:
    when: 'on_success'

job2:
  stage: prepare
  script:
    - echo 'running job'
  cache:
    when: 'on_failure'

job3:
  stage: prepare
  script:
    - echo 'running job'
  cache:
    when: 'always'
