---
data_category: operational
key_path: usage_activity_by_stage_monthly.secure.user_dependency_scanning_jobs
description: Monthly number of users creating Dependency Scanning jobs
product_section: sec
product_stage: secure
product_group: composition_analysis
product_category: dependency_scanning
value_type: number
status: active
time_frame: 28d
instrumentation_class: CountUsersCreatingCiBuildsMetric
options:
  secure_type: dependency_scanning
data_source: database
distribution:
- ee
tier:
- ultimate
performance_indicator_type:
- gmau
- paid_gmau
milestone: "<13.9"
