---
data_category: operational
key_path: usage_activity_by_stage_monthly.secure.user_sast_jobs
description: Users who run a SAST job
product_section: sec
product_stage: secure
product_group: static_analysis
product_category: static_application_security_testing
value_type: number
status: active
time_frame: 28d
instrumentation_class: CountUsersCreatingCiBuildsMetric
options:
  secure_type: sast
data_source: database
distribution:
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type:
- gmau
- paid_gmau
milestone: "<13.9"
