---
key_path: redis_hll_counters.analytics.g_analytics_ci_cd_deployment_frequency_monthly
name: g_analytics_ci_cd_deployment_frequency_monthly
description: Count of unique visits to the group level CI/CD Analytics Deloyment Frequency tab
product_section: dev
product_stage: manage
product_group: optimize
product_category:
value_type: number
status: active
milestone: "15.2"
introduced_by_url:
time_frame: 28d
data_source: redis_hll
data_category: operational
instrumentation_class: RedisHLLMetric
performance_indicator_type: []
distribution:
- ee
tier:
- premium
- ultimate
options:
  events:
    - g_analytics_ci_cd_deployment_frequency
