---
data_category: optional
key_path: counts.web_ide_pipelines
description: Count of Pipeline tab views in the Web IDE
product_section: dev
product_stage: create
product_group: editor
product_category: web_ide
value_type: number
status: active
time_frame: all
data_source: redis
instrumentation_class: RedisMetric
options:
  prefix: web_ide
  event: pipelines_count
  include_usage_prefix: false
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
