---
key_path: counts.i_code_review_merge_request_widget_test_summary_count_full_report_clicked
description: Total number of times the Test Summary widget extension Full Report button was clicked
product_section: dev
product_stage: create
product_group: code_review
product_category: code_review
value_type: number
status: active
milestone: "15.2"
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91831"
time_frame: all
data_source: redis
data_category: optional
options:
  events:
    - i_code_review_merge_request_widget_test_summary_count_full_report_clicked
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
