---
key_path: counts.i_code_review_merge_request_widget_license_compliance_count_expand_warning
description: Total number of times the License Compliance widget extension was expanded (while in its Warning state)
product_section: dev
product_stage: create
product_group: code_review
product_category: code_review
value_type: number
status: active
milestone: "15.4"
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96538"
time_frame: all
data_source: redis
data_category: optional
options:
  events:
    - i_code_review_merge_request_widget_license_compliance_count_expand_warning
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
