---
key_path: redis_hll_counters.code_review.i_code_review_merge_request_widget_code_quality_expand_failed_weekly
description: The count of unique users (weekly) who expanded the Code Quality widget extension while it is in its Failed state
product_section: dev
product_stage: create
product_group: code_review
product_category: code_review
value_type: number
status: active
milestone: "15.3"
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/93333"
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
options:
  events:
    - i_code_review_merge_request_widget_code_quality_expand_failed
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
