---
key_path: redis_hll_counters.testing.i_testing_test_report_uploaded_weekly
description: "MAU of junit test reports uploaded by customers per pipeline"
product_section: ops
product_stage: verify
product_group: pipeline_insights
product_category: testing
value_type: number
status: active
milestone: "15.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95112
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
options:
  events:
    - i_testing_test_report_uploaded
performance_indicator_type: []
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
