---
key_path: redis_hll_counters.error_tracking.error_tracking_total_unique_counts_weekly
description: Total unique users accessing error tracking routes
product_section: ops
product_stage: monitor
product_group: respond
product_category: error_tracking
value_type: number
status: active
milestone: "14.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82543
time_frame: 7d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
options:
  events:
    - error_tracking_view_list
    - error_tracking_view_details
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
