---
key_path: redis_hll_counters.ci_templates.p_ci_templates_security_fortify_fod_sast_monthly
description: Count of pipelines using the Fortify FoD SAST template
product_section: sec
product_stage: secure
product_group: static_analysis
product_category: SAST
value_type: number
status: active
milestone: "15.3"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91956
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_security_fortify_fod_sast
