---
key_path: redis_hll_counters.environments.users_visiting_environments_pages_monthly
description: Monthly count of unique users visiting environments pages
product_section: ops
product_stage: release
product_group: release
product_category: environment_management
value_type: number
status: active
milestone: "15.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97063
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
performance_indicator_type: []
options:
  events:
    - users_visiting_environments_pages
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
