---
key_path: redis_hll_counters.ci_templates.p_ci_templates_implicit_jobs_sast_iac_monthly
description: Count of pipelines with implicit SAST jobs using the stable SAST IaC template
product_section: sec
product_stage: secure
product_group: "static_analysis"
product_category: SAST
value_type: number
status: active
milestone: "15.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/86275
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
performance_indicator_type: []
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_implicit_jobs_sast_iac
