---
name: gitlab_gtm_datalayer
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/76305
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/348932
milestone: '14.6'
type: ops
group: group::buyer experience
default_enabled: false
