---
name: increase_branch_cache_expiry
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96739
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372331
milestone: '15.4'
type: ops
group: group::code review
default_enabled: false
