---
name: jira_raise_timeouts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/86439
rollout_issue_url: 
milestone: '15.0'
type: ops
group: group::integrations
default_enabled: false
