---
table_name: clusters_integration_prometheus
classes:
- Clusters::Integrations::Prometheus
feature_categories:
- incident_management
description: Persists information about prometheus cluster integration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/59091
milestone: '13.11'
