---
table_name: clusters_applications_cert_managers
classes:
- Clusters::Applications::CertManager
feature_categories:
- kubernetes_management
description: (Deprecated) A GitLab managed cert-manager installation in a Kubernetes cluster
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/commit/8837519445c319a699e0f3ced1c6912c839f3389
milestone: '11.6'
