---
table_name: deployment_merge_requests
classes:
- DeploymentMergeRequest
feature_categories:
- continuous_delivery
description: https://docs.gitlab.com/ee/ci/environments/index.html#track-newly-included-merge-requests-per-deployment
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18755
milestone: '12.5'
