---
table_name: dora_configurations
classes:
- Dora::Configuration
feature_categories:
- continuous_delivery
description: Stores project specific configurations for DORA4 calculations.
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96561
milestone: '15.4'
