---
table_name: issues_prometheus_alert_events
classes: []
feature_categories:
- incident_management
description: Adds relationship between PrometheusAlertEvent and issues created due to them
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17477
milestone: '12.4'
