---
table_name: namespace_settings
classes:
- NamespaceSetting
feature_categories:
- subgroups
description: Stores settings per namespace
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/36321
milestone: '13.2'
