---
table_name: pages_deployment_states
classes:
- Geo::PagesDeploymentState
feature_categories:
- pages
description: Stores verification state for Geo replicated Pages deployments.
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/74905
milestone: '14.6'
