---
table_name: project_alerting_settings
classes:
- Alerting::ProjectAlertingSetting
feature_categories:
- incident_management
description: Persists project-level tokens for manual Prometheus installations
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/9334
milestone: '11.8'
