---
table_name: redirect_routes
classes:
- RedirectRoute
feature_categories:
- projects
- subgroups
description: Stores routes for redirect after changing the path to group or project
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/11136
milestone: '9.2'
