---
table_name: routes
classes:
- Gitlab::Database::RenameReservedPathsMigration::V1::MigrationClasses::Route
- Route
feature_categories:
- projects
- subgroups
- users
description: Stores routes per namespaces and projects
introduced_by_url: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/7121
milestone: '9.0'
