---
data_category: operational
key_path: usage_activity_by_stage.secure.user_sast_jobs
description: Count of SAST jobs per user
product_section: sec
product_stage: secure
product_group: static_analysis
product_category: static_application_security_testing
value_type: number
status: active
time_frame: all
instrumentation_class: CountUsersCreatingCiBuildsMetric
options:
  secure_type: sast
data_source: database
distribution:
- ee
tier:
- free
- premium
- ultimate
milestone: "<13.9"
