---
data_category: operational
key_path: counts.secret_detection_jobs
description: Count of all 'secret-detection' CI jobs.
product_section: sec
product_stage: secure
product_group: static_analysis
product_category: secret_detection
value_type: number
status: active
time_frame: all
instrumentation_class: CountCiBuildsMetric
options:
  secure_type: secret_detection
data_source: database
distribution:
- ee
tier:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
