---
data_category: operational
key_path: counts.template_repositories
description: Count of total repo templates used to aggregate all file templates
product_section: dev
product_stage: create
product_group: source_code
product_category: source_code_management
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ee
tier:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
