---
data_category: operational
key_path: usage_activity_by_stage.secure.user_dependency_scanning_jobs
description: Total number of users running Dependency Scanning jobs
product_section: sec
product_stage: secure
product_group: composition_analysis
product_category: dependency_scanning
value_type: number
status: active
time_frame: all
instrumentation_class: CountUsersCreatingCiBuildsMetric
options:
  secure_type: dependency_scanning
data_source: database
distribution:
- ee
tier:
- ultimate
performance_indicator_type: []
milestone: "<13.9"
