---
data_category: operational
key_path: usage_activity_by_stage.secure.user_secret_detection_jobs
description: Count of Secret Detection Jobs per user
product_section: sec
product_stage: secure
product_group: static_analysis
product_category: secret_detection
value_type: number
status: active
time_frame: all
instrumentation_class: CountUsersCreatingCiBuildsMetric
options:
  secure_type: secret_detection
data_source: database
distribution:
- ee
tier:
- free
- premium
- ultimate
milestone: "<13.9"
