---
key_path: counts.i_code_review_merge_request_widget_metrics_count_expand_success
description: Total number of times the Metrics widget extension was expanded (while in its Success state)
product_section: dev
product_stage: create
product_group: code_review
product_category: code_review
value_type: number
status: active
milestone: "15.3"
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/94807"
time_frame: all
data_source: redis
data_category: optional
options:
  events:
    - i_code_review_merge_request_widget_metrics_count_expand_success
distribution:
- ee
tier:
- premium
- ultimate
